version: '3.1'

services:
  backend:
      build: ./apps/server
      ports:
        - "3000:3000"
      depends_on:
        - database
      environment:
        DATABASE_URL: postgres://mallone:root@database:5432/saas-client

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mallone
      POSTGRES_PASSWORD: root
